preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:
  jit-pack:
  #   阿里云 Google 存储库镜像
  aliyun-google-mirror:
  #   阿里云中央存储库镜像
  aliyun-maven-central-mirror:
  #   阿里云公共存储库镜像
  aliyun-maven-public-mirror:
  rovo89-xposed-api:
    scope: LIBRARIES
    url: https://api.xposed.info/
    content:
      include:
        group: de.robv.android.xposed

plugins:
  com.android.application:
    alias: android-application
    version: 8.12.2
  org.jetbrains.kotlin.android:
    alias: kotlin-android
    version: 2.2.10
  com.google.devtools.ksp:
    alias: kotlin-ksp
    version: 2.2.10-2.0.2

libraries:
  de.robv.android.xposed:
    api:
      version: 82
      repositories: rovo89-xposed-api
  com.highcapable.yukihookapi:
    api:
      version: 1.3.0
    ksp-xposed:
      version-ref: <this>::api
  com.highcapable.kavaref:
    kavaref-core:
      version: 1.0.1
    kavaref-extension:
      version: 1.0.1
  com.highcapable.hikage:
    hikage-core:
      version: 1.0.2
    hikage-compiler:
      version: 1.0.1
    hikage-extension:
      version: 1.0.1
    hikage-widget-androidx:
      version: 1.0.1
    hikage-widget-material:
      version: 1.0.1
  com.highcapable.betterandroid:
    ui-component:
      version: 1.0.8
    ui-extension:
      version: 1.0.7
    system-extension:
      version: 1.0.3
  com.github.duanhong169:
    drawabletoolbox:
      version: 1.0.7
  androidx.core:
    core-ktx:
      version: 1.17.0
  androidx.appcompat:
    appcompat:
      version: 1.7.1
  com.google.android.material:
    material:
      version: 1.12.0
  androidx.constraintlayout:
    constraintlayout:
      version: 2.2.1
  androidx.test.ext:
    junit:
      version: 1.3.0
  androidx.test.espresso:
    espresso-core:
      version: 3.7.0
  junit:
    junit:
      version: 4.13.2
  com.squareup.okhttp3:
    okhttp:
      version: 5.0.0-alpha.14
  com.google.code.gson:
    gson:
      version: 2.8.9
  org.luckypray:
    dexkit:
      version: 2.0.6
  org.slf4j:
    slf4j-api:
      version: 2.0.7
  com.github.tony19:
    logback-android:
      version: 3.0.0
#  androidx.compose.ui:
#    ui:
#      version: 1.9.0
#  androidx.compose.animation:
#    animation:
#      version: 1.9.0
#  androidx.compose.material:
#    material:
#      version: 1.9.0
#  androidx.compose.foundation:
#    foundation:
#      version: 1.9.0
#  androidx.compose.material3:
#    material3:
#      version: 1.3.2
#  androidx.compose.runtime:
#    runtime:
#      version: 1.9.0
#    runtime-livedata:
#      version: 1.9.0
#    runtime-rxjava2:
#      version: 1.9.0
